# Generated by Django 5.2.17 on 2026-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Латиница, для ссылки",
                        max_length=250,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="Обложка"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Показывается в списке и в превью для соцсетей",
                        max_length=400,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "excerpt_ru",
                    models.TextField(
                        help_text="Показывается в списке и в превью для соцсетей",
                        max_length=400,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "excerpt_ky",
                    models.TextField(
                        help_text="Показывается в списке и в превью для соцсетей",
                        max_length=400,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "excerpt_en",
                    models.TextField(
                        help_text="Показывается в списке и в превью для соцсетей",
                        max_length=400,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст статьи")),
                (
                    "content_ru",
                    models.TextField(null=True, verbose_name="Текст статьи"),
                ),
                (
                    "content_ky",
                    models.TextField(null=True, verbose_name="Текст статьи"),
                ),
                (
                    "content_en",
                    models.TextField(null=True, verbose_name="Текст статьи"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Внутри одной даты — меньше значит выше",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
            ],
            options={
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Блог",
                "ordering": ["-published_at", "order"],
            },
        ),
    ]
