# Generated by Django 5.2.17 on 2026-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mamralieva", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text='Только для типа "Внешняя ссылка" — куда ведёт кнопка "Подробнее"',
                max_length=500,
                verbose_name="Ссылка на источник",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("internal", "Статья на сайте"),
                    ("external", "Внешняя ссылка"),
                ],
                default="internal",
                max_length=10,
                verbose_name="Тип записи",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                blank=True,
                help_text='Только для типа "Статья на сайте"',
                verbose_name="Текст статьи",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_en",
            field=models.TextField(
                blank=True,
                help_text='Только для типа "Статья на сайте"',
                null=True,
                verbose_name="Текст статьи",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_ky",
            field=models.TextField(
                blank=True,
                help_text='Только для типа "Статья на сайте"',
                null=True,
                verbose_name="Текст статьи",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_ru",
            field=models.TextField(
                blank=True,
                help_text='Только для типа "Статья на сайте"',
                null=True,
                verbose_name="Текст статьи",
            ),
        ),
    ]
