# Generated by Django 6.0.1 on 2026-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=250, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "subtitle_ky",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Подзаголовок",
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Подзаголовок",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_ky",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "button_primary_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст основной кнопки"
                    ),
                ),
                (
                    "button_primary_text_ru",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Текст основной кнопки",
                    ),
                ),
                (
                    "button_primary_text_ky",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Текст основной кнопки",
                    ),
                ),
                (
                    "button_primary_text_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Текст основной кнопки",
                    ),
                ),
                (
                    "button_primary_url",
                    models.CharField(
                        blank=True,
                        default="#finder",
                        max_length=250,
                        verbose_name="Ссылка основной кнопки",
                    ),
                ),
                (
                    "button_secondary_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Текст дополнительной кнопки",
                    ),
                ),
                (
                    "button_secondary_text_ru",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Текст дополнительной кнопки",
                    ),
                ),
                (
                    "button_secondary_text_ky",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Текст дополнительной кнопки",
                    ),
                ),
                (
                    "button_secondary_text_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Текст дополнительной кнопки",
                    ),
                ),
                (
                    "button_secondary_url",
                    models.CharField(
                        blank=True,
                        default="#directions",
                        max_length=250,
                        verbose_name="Ссылка дополнительной кнопки",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Если не задано, будет использован стандартный темно-синий фон с абстрактным градиентом",
                        null=True,
                        upload_to="hero/",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Слайд главного экрана",
                "verbose_name_plural": "Слайды главного экрана",
                "ordering": ["order"],
            },
        ),
    ]
