# Generated by Django 6.0.1 on 2026-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_heroslide"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="conditions",
            field=models.TextField(
                blank=True,
                help_text="Каждое условие с новой строки",
                verbose_name="Условия работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="conditions_en",
            field=models.TextField(
                blank=True,
                help_text="Каждое условие с новой строки",
                null=True,
                verbose_name="Условия работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="conditions_ky",
            field=models.TextField(
                blank=True,
                help_text="Каждое условие с новой строки",
                null=True,
                verbose_name="Условия работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="conditions_ru",
            field=models.TextField(
                blank=True,
                help_text="Каждое условие с новой строки",
                null=True,
                verbose_name="Условия работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание вакансии"),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание вакансии"
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="description_ky",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание вакансии"
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание вакансии"
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="duties",
            field=models.TextField(
                blank=True,
                help_text="Каждая обязанность с новой строки",
                verbose_name="Обязанности",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="duties_en",
            field=models.TextField(
                blank=True,
                help_text="Каждая обязанность с новой строки",
                null=True,
                verbose_name="Обязанности",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="duties_ky",
            field=models.TextField(
                blank=True,
                help_text="Каждая обязанность с новой строки",
                null=True,
                verbose_name="Обязанности",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="duties_ru",
            field=models.TextField(
                blank=True,
                help_text="Каждая обязанность с новой строки",
                null=True,
                verbose_name="Обязанности",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="jobs/",
                verbose_name="Фото / Иллюстрация",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="requirements",
            field=models.TextField(
                blank=True,
                help_text="Каждое требование с новой строки",
                verbose_name="Требования",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="requirements_en",
            field=models.TextField(
                blank=True,
                help_text="Каждое требование с новой строки",
                null=True,
                verbose_name="Требования",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="requirements_ky",
            field=models.TextField(
                blank=True,
                help_text="Каждое требование с новой строки",
                null=True,
                verbose_name="Требования",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="requirements_ru",
            field=models.TextField(
                blank=True,
                help_text="Каждое требование с новой строки",
                null=True,
                verbose_name="Требования",
            ),
        ),
    ]
