# Generated by Django 6.0.1 on 2026-07-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_joblisting_conditions_joblisting_conditions_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
