# Generated by Django 6.0.1 on 2026-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_university_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="google_maps_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на Google Maps",
            ),
        ),
    ]
