# Generated by Django 5.2.17 on 2026-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_university_google_maps_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="age_range",
            field=models.CharField(
                blank=True,
                help_text="Например: от 18 до 35 лет",
                max_length=100,
                verbose_name="Возраст",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="age_range_en",
            field=models.CharField(
                blank=True,
                help_text="Например: от 18 до 35 лет",
                max_length=100,
                null=True,
                verbose_name="Возраст",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="age_range_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: от 18 до 35 лет",
                max_length=100,
                null=True,
                verbose_name="Возраст",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="age_range_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: от 18 до 35 лет",
                max_length=100,
                null=True,
                verbose_name="Возраст",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="documents_needed",
            field=models.TextField(
                blank=True,
                help_text="Например: загранпаспорт, анкета, видеорезюме",
                verbose_name="Какие документы нужны сразу",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="documents_needed_en",
            field=models.TextField(
                blank=True,
                help_text="Например: загранпаспорт, анкета, видеорезюме",
                null=True,
                verbose_name="Какие документы нужны сразу",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="documents_needed_ky",
            field=models.TextField(
                blank=True,
                help_text="Например: загранпаспорт, анкета, видеорезюме",
                null=True,
                verbose_name="Какие документы нужны сразу",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="documents_needed_ru",
            field=models.TextField(
                blank=True,
                help_text="Например: загранпаспорт, анкета, видеорезюме",
                null=True,
                verbose_name="Какие документы нужны сразу",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="flight",
            field=models.CharField(
                blank=True,
                help_text="Например: Авиаперелёт в обе стороны включён",
                max_length=150,
                verbose_name="Перелёт / транспорт",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="flight_en",
            field=models.CharField(
                blank=True,
                help_text="Например: Авиаперелёт в обе стороны включён",
                max_length=150,
                null=True,
                verbose_name="Перелёт / транспорт",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="flight_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: Авиаперелёт в обе стороны включён",
                max_length=150,
                null=True,
                verbose_name="Перелёт / транспорт",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="flight_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: Авиаперелёт в обе стороны включён",
                max_length=150,
                null=True,
                verbose_name="Перелёт / транспорт",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="housing",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                verbose_name="Жильё",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="housing_en",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                null=True,
                verbose_name="Жильё",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="housing_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                null=True,
                verbose_name="Жильё",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="housing_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                null=True,
                verbose_name="Жильё",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="meals",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                verbose_name="Питание",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="meals_en",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                null=True,
                verbose_name="Питание",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="meals_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                null=True,
                verbose_name="Питание",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="meals_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: Предоставляется бесплатно",
                max_length=150,
                null=True,
                verbose_name="Питание",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="processing_time",
            field=models.CharField(
                blank=True,
                help_text="Например: 2-3 мес",
                max_length=100,
                verbose_name="Сроки оформления",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="processing_time_en",
            field=models.CharField(
                blank=True,
                help_text="Например: 2-3 мес",
                max_length=100,
                null=True,
                verbose_name="Сроки оформления",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="processing_time_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: 2-3 мес",
                max_length=100,
                null=True,
                verbose_name="Сроки оформления",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="processing_time_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: 2-3 мес",
                max_length=100,
                null=True,
                verbose_name="Сроки оформления",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="recruitment_cost",
            field=models.CharField(
                blank=True,
                help_text="Например: 300 евро",
                max_length=100,
                verbose_name="Стоимость набора",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="recruitment_cost_en",
            field=models.CharField(
                blank=True,
                help_text="Например: 300 евро",
                max_length=100,
                null=True,
                verbose_name="Стоимость набора",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="recruitment_cost_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: 300 евро",
                max_length=100,
                null=True,
                verbose_name="Стоимость набора",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="recruitment_cost_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: 300 евро",
                max_length=100,
                null=True,
                verbose_name="Стоимость набора",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="recruitment_status",
            field=models.CharField(
                choices=[
                    ("open", "Актуально"),
                    ("closed", "Набор закрыт"),
                    ("soon", "Скоро"),
                ],
                default="open",
                max_length=10,
                verbose_name="Статус набора",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="required_gender",
            field=models.CharField(
                choices=[
                    ("any", "Мужчины и женщины"),
                    ("male", "Мужчины"),
                    ("female", "Женщины"),
                ],
                default="any",
                max_length=10,
                verbose_name="Требуются",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="visa_type",
            field=models.CharField(
                blank=True,
                help_text="Например: Сезонная виза (3+3 месяца)",
                max_length=150,
                verbose_name="Виза / документы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="visa_type_en",
            field=models.CharField(
                blank=True,
                help_text="Например: Сезонная виза (3+3 месяца)",
                max_length=150,
                null=True,
                verbose_name="Виза / документы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="visa_type_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: Сезонная виза (3+3 месяца)",
                max_length=150,
                null=True,
                verbose_name="Виза / документы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="visa_type_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: Сезонная виза (3+3 месяца)",
                max_length=150,
                null=True,
                verbose_name="Виза / документы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="work_schedule",
            field=models.CharField(
                blank=True,
                help_text="Например: Полный рабочий день",
                max_length=150,
                verbose_name="График работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="work_schedule_en",
            field=models.CharField(
                blank=True,
                help_text="Например: Полный рабочий день",
                max_length=150,
                null=True,
                verbose_name="График работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="work_schedule_ky",
            field=models.CharField(
                blank=True,
                help_text="Например: Полный рабочий день",
                max_length=150,
                null=True,
                verbose_name="График работы",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="work_schedule_ru",
            field=models.CharField(
                blank=True,
                help_text="Например: Полный рабочий день",
                max_length=150,
                null=True,
                verbose_name="График работы",
            ),
        ),
    ]
